Added more error codes

diff --git a/js/generator-aws-ecr/generators/app/templates/github/aws-ecr/action.yaml b/js/generator-aws-ecr/generators/app/templates/github/aws-ecr/action.yaml
--- a/js/generator-aws-ecr/generators/app/templates/github/aws-ecr/action.yaml
+++ b/js/generator-aws-ecr/generators/app/templates/github/aws-ecr/action.yaml
@@ -68,7 +68,7 @@ runs:
           echo "Sleeping to ensure bucket is available"
           sleep 60
           if [[ $? -ne 0 ]]; then
-            AppBuilder-Infrastructure-S3Failed The build script failed to create an S3 bucket to hold the Terraform state.
+            echo "AppBuilder-Infrastructure-S3Failed The build script failed to create an S3 bucket to hold the Terraform state. See https://github.com/OctopusSamples/content-team-apps/wiki/Error-Codes#appbuilder-infrastructure-s3failed for more information."        
           fi
         fi
       shell: "bash -l {0}" # Allow commands to fail by removing the default "-e" argument
@@ -105,6 +105,10 @@ runs:
         -var="aws_region=${{ inputs.aws_region }}"
         -var="aws_ecr_repository_name=${{ inputs.aws_ecr_repository_name }}"
         -var="github_repo_owner=${{ inputs.github_repo_owner }}"
+        
+        if [[ $? -ne 0 ]]; then
+          echo "AppBuilder-Infrastructure-ECRFailed The build script failed to create an ECR instance. See https://github.com/OctopusSamples/content-team-apps/wiki/Error-Codes#appbuilder-infrastructure-ecrfailed for more information."        
+        fi
       working-directory: terraform/aws-ecr
       shell: bash
 
