Fixed an issue with a missing output variable.

diff --git a/js/generator-aws-ecr/generators/app/templates/github/aws-ecr/action.yaml b/js/generator-aws-ecr/generators/app/templates/github/aws-ecr/action.yaml
--- a/js/generator-aws-ecr/generators/app/templates/github/aws-ecr/action.yaml
+++ b/js/generator-aws-ecr/generators/app/templates/github/aws-ecr/action.yaml
@@ -80,16 +80,39 @@ runs:
         fi
       shell: "bash -l {0}" # Allow commands to fail by removing the default "-e" argument
 
-    - name: Check registry already exists
+    # Terraform is bad at incorporating existing resources. Our testing often leaves existing ECR repositories in AWS,
+    # and it is nice to have this workflow reuse an existing repo rather than have every new test require the repo to
+    # be cleaned up.
+    #
+    # So here we determine if the Terraform state file exists that would have created an ECR instance,
+    # and if the ECR instance exists. If the ECR exists and the state file does not, we have an existing, unmanaged, ECR
+    # instance.
+
+    - name: Check registry already exists, and is created by terraform
       id: ecr_exists
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
         AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
       run: |
-        aws ecr describe-repositories --repository-names ${{ inputs.aws_ecr_repository_name}}-${${{inputs.github_repo_owner}},,}-${${{inputs.platform}},,} --region ${{ inputs.aws_region }}
-        EXISTS=$?
-        echo "::set-output name=EXISTS::${EXISTS}"
-      shell: bash
+        # Capture the variables. This allows us to use bash to do things like make the strings lowercase.
+        OWNER="${{inputs.github_repo_owner}}"
+        PLATFORM="${{inputs.platform}}"
+        # Check for the ecr repo
+        aws ecr describe-repositories --repository-names ${{ inputs.aws_ecr_repository_name}}-${OWNER,,}-${PLATFORM,,} --region ${{ inputs.aws_region }}
+        ECR_EXISTS=$?
+        echo "ECR Exists? ${ECR_EXISTS}"
+        # Check for the state file
+        aws s3api head-object --bucket app-builder-${{ inputs.terraform_bucket_suffix }} --key appbuilder-generator-aws-ecr --region ${{ inputs.terraform_bucket_region }} 2>/dev/null
+        STATE_FILE_EXISTS=$?
+        echo "State file exists? ${STATE_FILE_EXISTS}"
+        # We want to know if the ecr repo exists, and is not managed by the current terraform state file
+        [ ${ECR_EXISTS} == 0 ] && [ ${STATE_FILE_EXISTS} != 0 ]
+        EXISTS_AND_UNMANAGED=$?
+        echo "ECR exists and is unmanaged: ${EXISTS_AND_UNMANAGED}"
+        echo "::set-output name=EXISTS::${EXISTS_AND_UNMANAGED}"
+      shell: "bash -l {0}" # Allow commands to fail by removing the default "-e" argument
+
+    # Process variables in the backend terraform files
 
     - uses: danielr1996/envsubst-action@1.1.0
       env:
@@ -99,10 +122,18 @@ runs:
         input: terraform/aws-ecr/backend.tf
         output: terraform/aws-ecr/backend.tf
 
+    - uses: danielr1996/envsubst-action@1.1.0
+      env:
+        TERRAFORM_BUCKET_SUFFIX: ${{ inputs.terraform_bucket_suffix }}
+        TERRAFORM_BUCKET_REGION: ${{ inputs.terraform_bucket_region }}
+      with:
+        input: terraform/aws-ecr-existing/backend.tf
+        output: terraform/aws-ecr-existing/backend.tf
+
     # These steps are used when the registry does not exist
 
     - name: Terraform Init
-      if: steps.ecr_exists.outputs.EXISTS != 0
+      if: ${{ steps.ecr_exists.outputs.EXISTS != '0' }}
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
         AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
@@ -111,12 +142,12 @@ runs:
       shell: bash
 
     - name: Terraform Apply
-      if: steps.ecr_exists.outputs.EXISTS != 0
+      if: ${{ steps.ecr_exists.outputs.EXISTS != '0' }}
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
         AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
       run: |
-        terraform apply -auto-approve -var="ecr_exists=${{ steps.ecr_exists.outputs.EXISTS }}" -var="platform=${{ inputs.platform }}" -var="octopus_server=${{ inputs.octopus_server }}" -var="octopus_apikey=${{ inputs.octopus_apikey }}" -var="octopus_space_id=${{ inputs.octopus_space_id }}" -var="aws_access_key=${{ inputs.aws_access_key }}" -var="aws_secret_key=${{ inputs.aws_secret_key }}" -var="aws_region=${{ inputs.aws_region }}" -var="aws_region=${{ inputs.aws_region }}" -var="aws_ecr_repository_name=${{ inputs.aws_ecr_repository_name }}" -var="github_repo_owner=${{ inputs.github_repo_owner }}"
+        terraform apply -auto-approve -var="platform=${{ inputs.platform }}" -var="octopus_server=${{ inputs.octopus_server }}" -var="octopus_apikey=${{ inputs.octopus_apikey }}" -var="octopus_space_id=${{ inputs.octopus_space_id }}" -var="aws_access_key=${{ inputs.aws_access_key }}" -var="aws_secret_key=${{ inputs.aws_secret_key }}" -var="aws_region=${{ inputs.aws_region }}" -var="aws_region=${{ inputs.aws_region }}" -var="aws_ecr_repository_name=${{ inputs.aws_ecr_repository_name }}" -var="github_repo_owner=${{ inputs.github_repo_owner }}"
         
         if [[ $? -ne 0 ]]; then
           echo "AppBuilder-Infrastructure-ECRFailed The build script failed to create an ECR instance. See https://github.com/OctopusSamples/content-team-apps/wiki/Error-Codes#appbuilder-infrastructure-ecrfailed for more information."
@@ -125,40 +156,10 @@ runs:
       working-directory: terraform/aws-ecr
       shell: bash
 
-    - name: Terraform Collect ECR URL
-      if: steps.ecr_exists.outputs.EXISTS != 0
-      id: aws_ecr_repository_url
-      env:
-        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
-        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
-      run: terraform output -raw aws_ecr_repository_url
-      working-directory: terraform/aws-ecr
-      shell: bash
+    # These steps are used when the registry already exists
 
-    - name: Terraform Collect ECR Feed ID
-      if: steps.ecr_exists.outputs.EXISTS != 0
-      id: ecr_feed_id
-      env:
-        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
-        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
-      run: terraform output -raw ecr_feed_id
-      working-directory: terraform/aws-ecr
-      shell: bash
-
-    - name: Terraform Collect ECR URL
-      if: steps.ecr_exists.outputs.EXISTS != 0
-      id: aws_ecr_repository_name
-      env:
-        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
-        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
-      run: terraform output -raw aws_ecr_repository_name
-      working-directory: terraform/aws-ecr
-      shell: bash
-
-    # These steps are used when the registry already exist
-
-    - name: Terraform Init
-      if: steps.ecr_exists.outputs.EXISTS == 0
+    - name: Terraform Init (Existing ECR)
+      if: ${{ steps.ecr_exists.outputs.EXISTS == '0' }}
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
         AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
@@ -166,13 +167,13 @@ runs:
       working-directory: terraform/aws-ecr-existing
       shell: bash
 
-    - name: Terraform Apply
-      if: steps.ecr_exists.outputs.EXISTS == 0
+    - name: Terraform Apply (Existing ECR)
+      if: ${{ steps.ecr_exists.outputs.EXISTS == '0' }}
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
         AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
       run: |
-        terraform apply -auto-approve -var="ecr_exists=${{ steps.ecr_exists.outputs.EXISTS }}" -var="platform=${{ inputs.platform }}" -var="octopus_server=${{ inputs.octopus_server }}" -var="octopus_apikey=${{ inputs.octopus_apikey }}" -var="octopus_space_id=${{ inputs.octopus_space_id }}" -var="aws_access_key=${{ inputs.aws_access_key }}" -var="aws_secret_key=${{ inputs.aws_secret_key }}" -var="aws_region=${{ inputs.aws_region }}" -var="aws_region=${{ inputs.aws_region }}" -var="aws_ecr_repository_name=${{ inputs.aws_ecr_repository_name }}" -var="github_repo_owner=${{ inputs.github_repo_owner }}"
+        terraform apply -auto-approve -var="platform=${{ inputs.platform }}" -var="octopus_server=${{ inputs.octopus_server }}" -var="octopus_apikey=${{ inputs.octopus_apikey }}" -var="octopus_space_id=${{ inputs.octopus_space_id }}" -var="aws_access_key=${{ inputs.aws_access_key }}" -var="aws_secret_key=${{ inputs.aws_secret_key }}" -var="aws_region=${{ inputs.aws_region }}" -var="aws_region=${{ inputs.aws_region }}" -var="aws_ecr_repository_name=${{ inputs.aws_ecr_repository_name }}" -var="github_repo_owner=${{ inputs.github_repo_owner }}"
         
         if [[ $? -ne 0 ]]; then
           echo "AppBuilder-Infrastructure-ECRFailed The build script failed to create an ECR instance. See https://github.com/OctopusSamples/content-team-apps/wiki/Error-Codes#appbuilder-infrastructure-ecrfailed for more information."
@@ -181,32 +182,46 @@ runs:
       working-directory: terraform/aws-ecr-existing
       shell: bash
 
+    # Capture the output variables
+
     - name: Terraform Collect ECR URL
-      if: steps.ecr_exists.outputs.EXISTS == 0
       id: aws_ecr_repository_url
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
         AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
-      run: terraform output -raw aws_ecr_repository_url
-      working-directory: terraform/aws-ecr-existing
+      run: |
+        if [[ "${{ steps.ecr_exists.outputs.EXISTS }}" == "0" ]]; then
+          cd terraform/aws-ecr-existing
+        else
+          cd terraform/aws-ecr
+        fi
+        terraform output -raw aws_ecr_repository_url
       shell: bash
 
     - name: Terraform Collect ECR Feed ID
-      if: steps.ecr_exists.outputs.EXISTS == 0
       id: ecr_feed_id
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
         AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
-      run: terraform output -raw ecr_feed_id
-      working-directory: terraform/aws-ecr-existing
+      run: |
+        if [[ "${{ steps.ecr_exists.outputs.EXISTS }}" == "0" ]]; then
+          cd terraform/aws-ecr-existing
+        else
+          cd terraform/aws-ecr
+        fi
+        terraform output -raw ecr_feed_id
       shell: bash
 
     - name: Terraform Collect ECR URL
-      if: steps.ecr_exists.outputs.EXISTS == 0
       id: aws_ecr_repository_name
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
         AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
-      run: terraform output -raw aws_ecr_repository_name
-      working-directory: terraform/aws-ecr-existing
+      run: |
+        if [[ "${{ steps.ecr_exists.outputs.EXISTS }}" == "0" ]]; then
+          cd terraform/aws-ecr-existing
+        else
+          cd terraform/aws-ecr
+        fi
+        terraform output -raw aws_ecr_repository_name
       shell: bash
