Attempting to fix "Resource not accessible by integration" error. See https://githubmemory.com/repo/test-room-7/action-update-file/issues/10

diff --git a/js/generator-aws-ecr/generators/app/templates/github/aws-ecr/action.yaml b/js/generator-aws-ecr/generators/app/templates/github/aws-ecr/action.yaml
--- a/js/generator-aws-ecr/generators/app/templates/github/aws-ecr/action.yaml
+++ b/js/generator-aws-ecr/generators/app/templates/github/aws-ecr/action.yaml
@@ -80,6 +80,17 @@ runs:
         fi
       shell: "bash -l {0}" # Allow commands to fail by removing the default "-e" argument
 
+    - name: Check registry already exists
+      id: ecr_exists
+      env:
+        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
+        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
+      run: |
+        aws ecr describe-repositories --repository-names ${{ inputs.aws_ecr_repository_name}}-${${{inputs.github_repo_owner}},,}-${${{inputs.platform}},,} --region ${{ inputs.aws_region }}
+        EXISTS=$?
+        echo "::set-output name=EXISTS::${EXISTS}"
+      shell: bash
+
     - uses: danielr1996/envsubst-action@1.1.0
       env:
         TERRAFORM_BUCKET_SUFFIX: ${{ inputs.terraform_bucket_suffix }}
@@ -88,7 +99,10 @@ runs:
         input: terraform/aws-ecr/backend.tf
         output: terraform/aws-ecr/backend.tf
 
+    # These steps are used when the registry does not exist
+
     - name: Terraform Init
+      if: steps.ecr_exists.outputs.EXISTS != 0
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
         AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
@@ -97,11 +111,12 @@ runs:
       shell: bash
 
     - name: Terraform Apply
+      if: steps.ecr_exists.outputs.EXISTS != 0
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
         AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
       run: |
-        terraform apply -auto-approve -var="platform=${{ inputs.platform }}" -var="octopus_server=${{ inputs.octopus_server }}" -var="octopus_apikey=${{ inputs.octopus_apikey }}" -var="octopus_space_id=${{ inputs.octopus_space_id }}" -var="aws_access_key=${{ inputs.aws_access_key }}" -var="aws_secret_key=${{ inputs.aws_secret_key }}" -var="aws_region=${{ inputs.aws_region }}" -var="aws_region=${{ inputs.aws_region }}" -var="aws_ecr_repository_name=${{ inputs.aws_ecr_repository_name }}" -var="github_repo_owner=${{ inputs.github_repo_owner }}"
+        terraform apply -auto-approve -var="ecr_exists=${{ steps.ecr_exists.outputs.EXISTS }}" -var="platform=${{ inputs.platform }}" -var="octopus_server=${{ inputs.octopus_server }}" -var="octopus_apikey=${{ inputs.octopus_apikey }}" -var="octopus_space_id=${{ inputs.octopus_space_id }}" -var="aws_access_key=${{ inputs.aws_access_key }}" -var="aws_secret_key=${{ inputs.aws_secret_key }}" -var="aws_region=${{ inputs.aws_region }}" -var="aws_region=${{ inputs.aws_region }}" -var="aws_ecr_repository_name=${{ inputs.aws_ecr_repository_name }}" -var="github_repo_owner=${{ inputs.github_repo_owner }}"
         
         if [[ $? -ne 0 ]]; then
           echo "AppBuilder-Infrastructure-ECRFailed The build script failed to create an ECR instance. See https://github.com/OctopusSamples/content-team-apps/wiki/Error-Codes#appbuilder-infrastructure-ecrfailed for more information."
@@ -111,6 +126,7 @@ runs:
       shell: bash
 
     - name: Terraform Collect ECR URL
+      if: steps.ecr_exists.outputs.EXISTS != 0
       id: aws_ecr_repository_url
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
@@ -120,6 +136,7 @@ runs:
       shell: bash
 
     - name: Terraform Collect ECR Feed ID
+      if: steps.ecr_exists.outputs.EXISTS != 0
       id: ecr_feed_id
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
@@ -129,10 +146,67 @@ runs:
       shell: bash
 
     - name: Terraform Collect ECR URL
+      if: steps.ecr_exists.outputs.EXISTS != 0
       id: aws_ecr_repository_name
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
         AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
       run: terraform output -raw aws_ecr_repository_name
       working-directory: terraform/aws-ecr
+      shell: bash
+
+    # These steps are used when the registry already exist
+
+    - name: Terraform Init
+      if: steps.ecr_exists.outputs.EXISTS == 0
+      env:
+        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
+        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
+      run: terraform init
+      working-directory: terraform/aws-ecr-existing
+      shell: bash
+
+    - name: Terraform Apply
+      if: steps.ecr_exists.outputs.EXISTS == 0
+      env:
+        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
+        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
+      run: |
+        terraform apply -auto-approve -var="ecr_exists=${{ steps.ecr_exists.outputs.EXISTS }}" -var="platform=${{ inputs.platform }}" -var="octopus_server=${{ inputs.octopus_server }}" -var="octopus_apikey=${{ inputs.octopus_apikey }}" -var="octopus_space_id=${{ inputs.octopus_space_id }}" -var="aws_access_key=${{ inputs.aws_access_key }}" -var="aws_secret_key=${{ inputs.aws_secret_key }}" -var="aws_region=${{ inputs.aws_region }}" -var="aws_region=${{ inputs.aws_region }}" -var="aws_ecr_repository_name=${{ inputs.aws_ecr_repository_name }}" -var="github_repo_owner=${{ inputs.github_repo_owner }}"
+        
+        if [[ $? -ne 0 ]]; then
+          echo "AppBuilder-Infrastructure-ECRFailed The build script failed to create an ECR instance. See https://github.com/OctopusSamples/content-team-apps/wiki/Error-Codes#appbuilder-infrastructure-ecrfailed for more information."
+          exit 1
+        fi
+      working-directory: terraform/aws-ecr-existing
+      shell: bash
+
+    - name: Terraform Collect ECR URL
+      if: steps.ecr_exists.outputs.EXISTS == 0
+      id: aws_ecr_repository_url
+      env:
+        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
+        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
+      run: terraform output -raw aws_ecr_repository_url
+      working-directory: terraform/aws-ecr-existing
+      shell: bash
+
+    - name: Terraform Collect ECR Feed ID
+      if: steps.ecr_exists.outputs.EXISTS == 0
+      id: ecr_feed_id
+      env:
+        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
+        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
+      run: terraform output -raw ecr_feed_id
+      working-directory: terraform/aws-ecr-existing
+      shell: bash
+
+    - name: Terraform Collect ECR URL
+      if: steps.ecr_exists.outputs.EXISTS == 0
+      id: aws_ecr_repository_name
+      env:
+        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
+        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
+      run: terraform output -raw aws_ecr_repository_name
+      working-directory: terraform/aws-ecr-existing
       shell: bash
