Added more checks

diff --git a/js/generator-github-shared-infrastructure/generators/app/templates/github/shared-infrastructure/action.yaml b/js/generator-github-shared-infrastructure/generators/app/templates/github/shared-infrastructure/action.yaml
--- a/js/generator-github-shared-infrastructure/generators/app/templates/github/shared-infrastructure/action.yaml
+++ b/js/generator-github-shared-infrastructure/generators/app/templates/github/shared-infrastructure/action.yaml
@@ -122,17 +122,13 @@ runs:
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
         AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
-      run: >
-        terraform apply 
-        -auto-approve 
-        -var="octopus_server=${{ inputs.octopus_server }}" 
-        -var="octopus_apikey=${{ inputs.octopus_apikey }}"
-        -var="octopus_space_id=${{ inputs.octopus_space_id }}"
-        -var="aws_access_key=${{ inputs.aws_access_key }}"
-        -var="aws_secret_key=${{ inputs.aws_secret_key }}"
-        -var="aws_region=${{ inputs.aws_region }}"
-        -var="github_repo=${{ inputs.github_repo }}"
-        -var="github_username=${{ inputs.github_username }}"
+      run: |
+        terraform apply -auto-approve -var="octopus_server=${{ inputs.octopus_server }}" -var="octopus_apikey=${{ inputs.octopus_apikey }}" -var="octopus_space_id=${{ inputs.octopus_space_id }}" -var="aws_access_key=${{ inputs.aws_access_key }}" -var="aws_secret_key=${{ inputs.aws_secret_key }}" -var="aws_region=${{ inputs.aws_region }}" -var="github_repo=${{ inputs.github_repo }}" -var="github_username=${{ inputs.github_username }}"
+        
+        if [[ $? -ne 0 ]]; then
+          echo "AppBuilder-Infrastructure-OctopusSharedResourceFailed The build script failed to populate the Octopus instance. See https://github.com/OctopusSamples/content-team-apps/wiki/Error-Codes#appbuilder-infrastructure-octopussharedresourcefailed for more information."
+          exit 1
+        fi
       working-directory: terraform/shared-infrastructure
       shell: bash
 
